namespace sistemapersonaltrainer.Server.Enums
{
    enum EquipmentEnum
    {
        AbWheel = 1,
        Barbell = 2,
        BattleRopes = 3,
        BenchDecline = 4,
        BenchFlat = 5,
        BenchIncline = 6,
        Bodyweight = 7,
        BulgarianBag = 8,
        Cable = 9,
        ClimbingRope = 10,
        Clubbell = 11,
        Dumbbell = 12,
        EZBar = 13,
        GravityBoots = 14,
        GymnasticRings = 15,
        HeavySandbag = 16,
        IndianClub = 17,
        Kettlebell = 18,
        Landmine = 19,
        Macebell = 20,
        MedicineBall = 21,
        Miniband = 22,
        ParalletteBars = 23,
        PlyoBox = 24,
        PullUpBar = 25,
        ResistanceBand = 26,
        Sandbag = 27,
        SlamBall = 28,
        SlantBoard = 29,
        Sled = 30,
        SledgeHammer = 31,
        Sliders = 32,
        StabilityBall = 33,
        Superband = 34,
        SuspensionTrainer = 35,
        Tire = 36,
        TrapBar = 37,
        WallBall = 38,
        WeightPlate = 39,
        None = 40
    }
}
