namespace sistemapersonaltrainer.Server.Enums
{
    enum MuscleEnum
    {
        AdductorMagnus = 1,
        AnteriorDeltoids = 2,
        BicepsBrachii = 3,
        BicepsFemoris = 4,
        Brachialis = 5,
        Brachioradialis = 6,
        ErectorSpinae = 7,
        ExtensorHallucisLongus = 8,
        FlexorCarpiRadialis = 9,
        Gastrocnemius = 10,
        GluteusMaximus = 11,
        GluteusMedius = 12,
        GluteusMinimus = 13,
        Iliopsoas = 14,
        LatissimusDorsi = 15,
        Obliques = 16,
        PectoralisMajor = 17,
        PosteriorDeltoids = 18,
        QuadricepsFemoris = 19,
        RectusAbdominis = 20,
        RectusFemoris = 21,
        Rhomboids = 22,
        SerratusAnterior = 23,
        Soleus = 24,
        TensorFasciaeLatae = 25,
        TeresMajor = 26,
        TeresMinor = 27,
        TibialisAnterior = 28,
        TibialisPosterior = 29,
        TransverseAbdominis = 30,
        Trapezius = 31,
        TricepsBrachii = 32,
        UpperTrapezius = 33,
        LateralDeltoids = 34,
        Anconeus = 35,
        Infraspinatus = 36,
        LevatorScapulae = 37,
        ExtensorDigitorumLongus = 38,
        Supraspinatus = 39,
        MedialDeltoids = 40,
        Subscapularis = 41,
        VastusMediais = 42
    }
}
