namespace sistemapersonaltrainer.Server.Enums
{
    enum PatternEnum
    {
        AnkleDorsiflexion = 1,
        AnklePlantarFlexion = 2,
        AntiExtension = 3,
        AntiFlexion = 4,
        AntiLateralFlexion = 5,
        AntiRotational = 6,
        ElbowExtension = 7,
        ElbowFlexion = 8,
        HipAbduction = 9,
        HipAdduction = 10,
        HipDominant = 11,
        HipExtension = 12,
        HipExternalRotation = 13,
        HipFlexion = 14,
        HipHinge = 15,
        HorizontalAdduction = 16,
        HorizontalPull = 17,
        HorizontalPush = 18,
        IsometricHold = 19,
        KneeDominant = 20,
        LateralFlexion = 21,
        LateralLocomotion = 22,
        LoadedCarry = 23,
        Locomotion = 24,
        Other = 25,
        Rotational = 26,
        ScapularElevation = 27,
        ShoulderAbduction = 28,
        ShoulderExternalRotation = 29,
        ShoulderFlexion = 30,
        ShoulderInternalRotation = 31,
        ShoulderScapularPlaneElevation = 32,
        SpinalExtension = 33,
        SpinalFlexion = 34,
        SpinalRotational = 35,
        Unsorted = 36,
        VerticalPull = 37,
        VerticalPush = 38,
        WristExtension = 39,
        WristFlexion = 40,
        HipInternalRotation = 41
    }
}
