// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sistemapersonaltrainer.Server.Data;

#nullable disable

namespace sistemapersonaltrainer.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250930163308_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.BodyRegion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("BodyRegions");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.CombinationExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CombinationExercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("IMC")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.DifficultyLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DifficultyLevels");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BodyRegionId")
                        .HasColumnType("int");

                    b.Property<int?>("CombinationExerciseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("DifficultyLevelId")
                        .HasColumnType("int");

                    b.Property<int?>("ExerciseArmModeId")
                        .HasColumnType("int");

                    b.Property<int?>("ExerciseArmTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("ExerciseClassificationId")
                        .HasColumnType("int");

                    b.Property<int?>("ExerciseLegModeId")
                        .HasColumnType("int");

                    b.Property<int?>("FootElevationId")
                        .HasColumnType("int");

                    b.Property<int?>("ForceTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("GripId")
                        .HasColumnType("int");

                    b.Property<int?>("LateralityId")
                        .HasColumnType("int");

                    b.Property<int?>("LoadPositionEndId")
                        .HasColumnType("int");

                    b.Property<int?>("MechanicId")
                        .HasColumnType("int");

                    b.Property<int?>("MuscleGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("PostureId")
                        .HasColumnType("int");

                    b.Property<int?>("PrimaryEquipmentId")
                        .HasColumnType("int");

                    b.Property<int?>("PrimaryItems")
                        .HasColumnType("int");

                    b.Property<int?>("PrimaryPatternId")
                        .HasColumnType("int");

                    b.Property<int?>("PrimaryPlaneOfMotionId")
                        .HasColumnType("int");

                    b.Property<int?>("PrimeMoverMuscleId")
                        .HasColumnType("int");

                    b.Property<int?>("SecondaryEquipmentId")
                        .HasColumnType("int");

                    b.Property<int?>("SecondaryItems")
                        .HasColumnType("int");

                    b.Property<int?>("SecondaryMoverMuscleId")
                        .HasColumnType("int");

                    b.Property<int?>("SecondaryPatternId")
                        .HasColumnType("int");

                    b.Property<int?>("SecondaryPlaneOfMotionId")
                        .HasColumnType("int");

                    b.Property<int?>("TertiaryMoverMuscleId")
                        .HasColumnType("int");

                    b.Property<int?>("TertiaryPatternId")
                        .HasColumnType("int");

                    b.Property<int?>("TertiaryPlaneOfMotionId")
                        .HasColumnType("int");

                    b.Property<string>("UrlLongVideo")
                        .HasColumnType("longtext");

                    b.Property<string>("UrlShortVideo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BodyRegionId");

                    b.HasIndex("CombinationExerciseId");

                    b.HasIndex("DifficultyLevelId");

                    b.HasIndex("ExerciseArmModeId");

                    b.HasIndex("ExerciseArmTypeId");

                    b.HasIndex("ExerciseClassificationId");

                    b.HasIndex("ExerciseLegModeId");

                    b.HasIndex("FootElevationId");

                    b.HasIndex("ForceTypeId");

                    b.HasIndex("GripId");

                    b.HasIndex("LateralityId");

                    b.HasIndex("LoadPositionEndId");

                    b.HasIndex("MechanicId");

                    b.HasIndex("MuscleGroupId");

                    b.HasIndex("PostureId");

                    b.HasIndex("PrimaryEquipmentId");

                    b.HasIndex("PrimaryPatternId");

                    b.HasIndex("PrimaryPlaneOfMotionId");

                    b.HasIndex("PrimeMoverMuscleId");

                    b.HasIndex("SecondaryEquipmentId");

                    b.HasIndex("SecondaryMoverMuscleId");

                    b.HasIndex("SecondaryPatternId");

                    b.HasIndex("SecondaryPlaneOfMotionId");

                    b.HasIndex("TertiaryMoverMuscleId");

                    b.HasIndex("TertiaryPatternId");

                    b.HasIndex("TertiaryPlaneOfMotionId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.ExerciseArmType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ExerciseArmTypes");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.ExerciseClassification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ExerciseCalifications");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.ExerciseMode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ExerciseModes");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.FootElevation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FootElevations");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.ForceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ForceTypes");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Grip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Grips");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Laterality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Lateralities");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.LoadPositionEnd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("LoadPositionEnds");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Mechanic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Mechanics");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Muscle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Muscles");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.MuscleGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MuscleGroups");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Pattern", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Patterns");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.PlaneOfMotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PlaneOfMotions");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Posture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Postures");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "maximiliano_hermosilla@hotmail.com",
                            Enabled = true,
                            LastName = "Sistemas",
                            Name = "Administrador",
                            Password = "U+QpQHyCKuYC78AAH05KwA==",
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "isaias.luque@mayidev.com",
                            Enabled = true,
                            LastName = "Luque",
                            Name = "Isaias",
                            Password = "U+QpQHyCKuYC78AAH05KwA==",
                            UserName = "isaiasLuque"
                        });
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("UserId");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.WorkoutActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutActivities");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.WorkoutActivityExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("Repetitions")
                        .HasColumnType("int");

                    b.Property<int?>("RestMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("Series")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutActivityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutActivityId");

                    b.ToTable("WorkoutActivityExercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Exercise", b =>
                {
                    b.HasOne("sistemapersonaltrainer.Server.Models.BodyRegion", "BodyRegion")
                        .WithMany("Exercises")
                        .HasForeignKey("BodyRegionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.CombinationExercise", "CombinationExercise")
                        .WithMany("Exercises")
                        .HasForeignKey("CombinationExerciseId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.DifficultyLevel", "DifficultyLevel")
                        .WithMany("Exercises")
                        .HasForeignKey("DifficultyLevelId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.ExerciseMode", "ExerciseArmMode")
                        .WithMany("ArmExercises")
                        .HasForeignKey("ExerciseArmModeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.ExerciseArmType", "ExerciseArmType")
                        .WithMany("Exercises")
                        .HasForeignKey("ExerciseArmTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.ExerciseClassification", "ExerciseClassification")
                        .WithMany("Exercises")
                        .HasForeignKey("ExerciseClassificationId");

                    b.HasOne("sistemapersonaltrainer.Server.Models.ExerciseMode", "ExerciseLegMode")
                        .WithMany("LegExercises")
                        .HasForeignKey("ExerciseLegModeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.FootElevation", "FootElevation")
                        .WithMany("Exercises")
                        .HasForeignKey("FootElevationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.ForceType", "ForceType")
                        .WithMany("Exercises")
                        .HasForeignKey("ForceTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.Grip", "Grip")
                        .WithMany("Exercises")
                        .HasForeignKey("GripId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.Laterality", "Laterality")
                        .WithMany("Exercises")
                        .HasForeignKey("LateralityId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.LoadPositionEnd", "LoadPositionEnd")
                        .WithMany("Exercises")
                        .HasForeignKey("LoadPositionEndId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.Mechanic", "Mechanic")
                        .WithMany("Exercises")
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.MuscleGroup", "MuscleGroup")
                        .WithMany("Exercises")
                        .HasForeignKey("MuscleGroupId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.Posture", "Posture")
                        .WithMany("Exercises")
                        .HasForeignKey("PostureId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.Equipment", "PrimaryEquipment")
                        .WithMany("PrimaryExercises")
                        .HasForeignKey("PrimaryEquipmentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.Pattern", "PrimaryPattern")
                        .WithMany("PrimaryExercises")
                        .HasForeignKey("PrimaryPatternId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.PlaneOfMotion", "PrimaryPlaneOfMotion")
                        .WithMany("PrimaryExercises")
                        .HasForeignKey("PrimaryPlaneOfMotionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.Muscle", "PrimeMoverMuscle")
                        .WithMany("PrimeMoverExercises")
                        .HasForeignKey("PrimeMoverMuscleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.Equipment", "SecondaryEquipment")
                        .WithMany("SecondaryExercises")
                        .HasForeignKey("SecondaryEquipmentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.Muscle", "SecondaryMoverMuscle")
                        .WithMany("SecondaryMoverExercises")
                        .HasForeignKey("SecondaryMoverMuscleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.Pattern", "SecondaryPattern")
                        .WithMany("SecondaryExercises")
                        .HasForeignKey("SecondaryPatternId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.PlaneOfMotion", "SecondaryPlaneOfMotion")
                        .WithMany("SecondaryExercises")
                        .HasForeignKey("SecondaryPlaneOfMotionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.Muscle", "TertiaryMoverMuscle")
                        .WithMany("TertiaryMoverExercises")
                        .HasForeignKey("TertiaryMoverMuscleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.Pattern", "TertiaryPattern")
                        .WithMany("TertiaryExercises")
                        .HasForeignKey("TertiaryPatternId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.PlaneOfMotion", "TertiaryPlaneOfMotion")
                        .WithMany("TertiaryExercises")
                        .HasForeignKey("TertiaryPlaneOfMotionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("BodyRegion");

                    b.Navigation("CombinationExercise");

                    b.Navigation("DifficultyLevel");

                    b.Navigation("ExerciseArmMode");

                    b.Navigation("ExerciseArmType");

                    b.Navigation("ExerciseClassification");

                    b.Navigation("ExerciseLegMode");

                    b.Navigation("FootElevation");

                    b.Navigation("ForceType");

                    b.Navigation("Grip");

                    b.Navigation("Laterality");

                    b.Navigation("LoadPositionEnd");

                    b.Navigation("Mechanic");

                    b.Navigation("MuscleGroup");

                    b.Navigation("Posture");

                    b.Navigation("PrimaryEquipment");

                    b.Navigation("PrimaryPattern");

                    b.Navigation("PrimaryPlaneOfMotion");

                    b.Navigation("PrimeMoverMuscle");

                    b.Navigation("SecondaryEquipment");

                    b.Navigation("SecondaryMoverMuscle");

                    b.Navigation("SecondaryPattern");

                    b.Navigation("SecondaryPlaneOfMotion");

                    b.Navigation("TertiaryMoverMuscle");

                    b.Navigation("TertiaryPattern");

                    b.Navigation("TertiaryPlaneOfMotion");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Workout", b =>
                {
                    b.HasOne("sistemapersonaltrainer.Server.Models.Customer", "Customer")
                        .WithMany("Workouts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("sistemapersonaltrainer.Server.Models.User", "User")
                        .WithMany("Workouts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.WorkoutActivity", b =>
                {
                    b.HasOne("sistemapersonaltrainer.Server.Models.Workout", "Workout")
                        .WithMany("WorkoutActivities")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.WorkoutActivityExercise", b =>
                {
                    b.HasOne("sistemapersonaltrainer.Server.Models.Exercise", "Exercise")
                        .WithMany("WorkoutActivityExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("sistemapersonaltrainer.Server.Models.WorkoutActivity", "WorkoutActivity")
                        .WithMany("WorkoutActivityExercises")
                        .HasForeignKey("WorkoutActivityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutActivity");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.BodyRegion", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.CombinationExercise", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Customer", b =>
                {
                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.DifficultyLevel", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Equipment", b =>
                {
                    b.Navigation("PrimaryExercises");

                    b.Navigation("SecondaryExercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Exercise", b =>
                {
                    b.Navigation("WorkoutActivityExercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.ExerciseArmType", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.ExerciseClassification", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.ExerciseMode", b =>
                {
                    b.Navigation("ArmExercises");

                    b.Navigation("LegExercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.FootElevation", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.ForceType", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Grip", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Laterality", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.LoadPositionEnd", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Mechanic", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Muscle", b =>
                {
                    b.Navigation("PrimeMoverExercises");

                    b.Navigation("SecondaryMoverExercises");

                    b.Navigation("TertiaryMoverExercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.MuscleGroup", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Pattern", b =>
                {
                    b.Navigation("PrimaryExercises");

                    b.Navigation("SecondaryExercises");

                    b.Navigation("TertiaryExercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.PlaneOfMotion", b =>
                {
                    b.Navigation("PrimaryExercises");

                    b.Navigation("SecondaryExercises");

                    b.Navigation("TertiaryExercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Posture", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.User", b =>
                {
                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Workout", b =>
                {
                    b.Navigation("WorkoutActivities");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.WorkoutActivity", b =>
                {
                    b.Navigation("WorkoutActivityExercises");
                });
#pragma warning restore 612, 618
        }
    }
}
