// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sistemapersonaltrainer.Server.Data;

#nullable disable

namespace sistemapersonaltrainer.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.BodyRegion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("BodyRegions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Centro",
                            Name = "Core"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Cuerpo Completo",
                            Name = "Full Body"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Cuerpo Inferior",
                            Name = "Lower Body"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Cuerpo Superior",
                            Name = "Upper Body"
                        });
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.CombinationExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CombinationExercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Ejercicio Combinado",
                            Name = "Combo Exercise"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Ejercicio Simple",
                            Name = "Single Exercise"
                        });
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("IMC")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.DifficultyLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DifficultyLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Avanzado",
                            Name = "Advanced"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Principiante",
                            Name = "Beginner"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Experto",
                            Name = "Expert"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Gran Maestro",
                            Name = "Grand Master"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Intermedio",
                            Name = "Intermediate"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Legendario",
                            Name = "Legendary"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Maestro",
                            Name = "Master"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Novato",
                            Name = "Novice"
                        });
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ab Wheel"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Barbell"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Battle Ropes"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bench (Decline)"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bench (Flat)"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Bench (Incline)"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Bodyweight"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Bulgarian Bag"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Cable"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Climbing Rope"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Clubbell"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Dumbbell"
                        },
                        new
                        {
                            Id = 13,
                            Name = "EZ Bar"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Gravity Boots"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Gymnastic Rings"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Heavy Sandbag"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Indian Club"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Kettlebell"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Landmine"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Macebell"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Medicine Ball"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Miniband"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Parallette Bars"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Plyo Box"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Pull Up Bar"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Resistance Band"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Sandbag"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Slam Ball"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Slant Board"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Sled"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Sledge Hammer"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Sliders"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Stability Ball"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Superband"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Suspension Trainer"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Tire"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Trap Bar"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Wall Ball"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Weight Plate"
                        },
                        new
                        {
                            Id = 40,
                            Name = "None"
                        });
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BodyRegionId")
                        .HasColumnType("int");

                    b.Property<int?>("CombinationExerciseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("DifficultyLevelId")
                        .HasColumnType("int");

                    b.Property<int?>("ExerciseArmModeId")
                        .HasColumnType("int");

                    b.Property<int?>("ExerciseArmTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("ExerciseClassificationId")
                        .HasColumnType("int");

                    b.Property<int?>("ExerciseLegModeId")
                        .HasColumnType("int");

                    b.Property<int?>("FootElevationId")
                        .HasColumnType("int");

                    b.Property<int?>("ForceTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("GripId")
                        .HasColumnType("int");

                    b.Property<int?>("LateralityId")
                        .HasColumnType("int");

                    b.Property<int?>("LoadPositionEndId")
                        .HasColumnType("int");

                    b.Property<int?>("MechanicId")
                        .HasColumnType("int");

                    b.Property<int?>("MuscleGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("PostureId")
                        .HasColumnType("int");

                    b.Property<int?>("PrimaryEquipmentId")
                        .HasColumnType("int");

                    b.Property<int?>("PrimaryItems")
                        .HasColumnType("int");

                    b.Property<int?>("PrimaryPatternId")
                        .HasColumnType("int");

                    b.Property<int?>("PrimaryPlaneOfMotionId")
                        .HasColumnType("int");

                    b.Property<int?>("PrimeMoverMuscleId")
                        .HasColumnType("int");

                    b.Property<int?>("SecondaryEquipmentId")
                        .HasColumnType("int");

                    b.Property<int?>("SecondaryItems")
                        .HasColumnType("int");

                    b.Property<int?>("SecondaryMoverMuscleId")
                        .HasColumnType("int");

                    b.Property<int?>("SecondaryPatternId")
                        .HasColumnType("int");

                    b.Property<int?>("SecondaryPlaneOfMotionId")
                        .HasColumnType("int");

                    b.Property<int?>("TertiaryMoverMuscleId")
                        .HasColumnType("int");

                    b.Property<int?>("TertiaryPatternId")
                        .HasColumnType("int");

                    b.Property<int?>("TertiaryPlaneOfMotionId")
                        .HasColumnType("int");

                    b.Property<string>("UrlLongVideo")
                        .HasColumnType("longtext");

                    b.Property<string>("UrlShortVideo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BodyRegionId");

                    b.HasIndex("CombinationExerciseId");

                    b.HasIndex("DifficultyLevelId");

                    b.HasIndex("ExerciseArmModeId");

                    b.HasIndex("ExerciseArmTypeId");

                    b.HasIndex("ExerciseClassificationId");

                    b.HasIndex("ExerciseLegModeId");

                    b.HasIndex("FootElevationId");

                    b.HasIndex("ForceTypeId");

                    b.HasIndex("GripId");

                    b.HasIndex("LateralityId");

                    b.HasIndex("LoadPositionEndId");

                    b.HasIndex("MechanicId");

                    b.HasIndex("MuscleGroupId");

                    b.HasIndex("PostureId");

                    b.HasIndex("PrimaryEquipmentId");

                    b.HasIndex("PrimaryPatternId");

                    b.HasIndex("PrimaryPlaneOfMotionId");

                    b.HasIndex("PrimeMoverMuscleId");

                    b.HasIndex("SecondaryEquipmentId");

                    b.HasIndex("SecondaryMoverMuscleId");

                    b.HasIndex("SecondaryPatternId");

                    b.HasIndex("SecondaryPlaneOfMotionId");

                    b.HasIndex("TertiaryMoverMuscleId");

                    b.HasIndex("TertiaryPatternId");

                    b.HasIndex("TertiaryPlaneOfMotionId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.ExerciseArmType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ExerciseArmTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Doble brazo",
                            Name = "Double Arm"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sin brazos",
                            Name = "No Arms"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Un brazo",
                            Name = "Single Arm"
                        });
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.ExerciseClassification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ExerciseClassifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Flujo animal",
                            Name = "Animal Flow"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Equilibrio",
                            Name = "Balance"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Ejercicios balísticos",
                            Name = "Ballistics"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Culturismo",
                            Name = "Bodybuilding"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Calistenia",
                            Name = "Calisthenics"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Movimientos de fuerza sostenida",
                            Name = "Grinds"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Movilidad",
                            Name = "Mobility"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Halterofilia",
                            Name = "Olympic Weightlifting"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Halterofilia",
                            Name = "Olympic Weightlifting "
                        },
                        new
                        {
                            Id = 10,
                            Description = "Pliometría",
                            Name = "Plyometric"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Postural",
                            Name = "Postural"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Levantamiento de potencia",
                            Name = "Powerlifting"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Sin clasificar",
                            Name = "Unsorted*"
                        });
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.ExerciseMode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ExerciseModes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Alternando",
                            Name = "Alternating"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Continuo",
                            Name = "Continuous"
                        });
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.FootElevation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FootElevations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Pies Elevados",
                            Name = "Feet Elevated"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Pie Elevado",
                            Name = "Foot Elevated"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Pie Elevado (Frontal)",
                            Name = "Foot Elevated (Front)"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Pie Elevado (Lateral)",
                            Name = "Foot Elevated (Lateral)"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Pie Elevado (Trasero)",
                            Name = "Foot Elevated (Rear)"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Pie Elevado (De costado)",
                            Name = "Foot Elevated (Side)"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Tacones elevados",
                            Name = "Heels Elevated"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Sin elevación",
                            Name = "No Elevation"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Dedos elevados",
                            Name = "Toes Elevated"
                        });
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.ForceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ForceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Otro",
                            Name = "Other"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Tirar",
                            Name = "Pull"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Empujar",
                            Name = "Push"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Empujar y Tirar",
                            Name = "Push & Pull"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Sin clasificar*",
                            Name = "Unsorted*"
                        });
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Grip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Grips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Con agarrón hacia arriba",
                            Name = "Bottoms Up"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Agarre de cuerno invertido",
                            Name = "Bottoms Up Horn Grip"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Agarre de aplastamiento",
                            Name = "Crush Grip"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Agarre falso",
                            Name = "False Grip"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Agarre con las yemas de los dedos",
                            Name = "Fingertip"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Palma plana",
                            Name = "Flat Palm"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Agarre con el antebrazo",
                            Name = "Forearm"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Agarre de copa",
                            Name = "Goblet"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Agarre con asistencia de la mano",
                            Name = "Hand Assisted"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Agarre con apoyo en la cabeza",
                            Name = "Head Supported"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Agarre de cuerno",
                            Name = "Horn Grip"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Agarre mixto",
                            Name = "Mixed Grip"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Agarre neutral o de martillo",
                            Name = "Neutral"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Sin agarre",
                            Name = "No Grip"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Otro",
                            Name = "Other"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Agarre pronado (palmas hacia abajo)",
                            Name = "Pronated"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Agarre supinado (palmas hacia arriba)",
                            Name = "Supinated"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Agarre de camarero",
                            Name = "Waiter Hold"
                        });
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Laterality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Lateralities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Bilateral",
                            Name = "Bilateral"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Contralateral",
                            Name = "Contralateral"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Ipsolateral",
                            Name = "Ipsilateral"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Unilateral",
                            Name = "Unilateral"
                        });
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.LoadPositionEnd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("LoadPositionEnds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Por encima del pecho",
                            Name = "Above Chest"
                        },
                        new
                        {
                            Id = 2,
                            Description = "En rack trasero",
                            Name = "Back Rack"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Abrazo de oso",
                            Name = "Bear Hug"
                        },
                        new
                        {
                            Id = 4,
                            Description = "A la espalda",
                            Name = "Behind Back"
                        },
                        new
                        {
                            Id = 5,
                            Description = "En rack frontal",
                            Name = "Front Rack"
                        },
                        new
                        {
                            Id = 6,
                            Description = "En el pliegue de la cadera",
                            Name = "Hip Crease"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Lateral",
                            Name = "Lateral"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Sostenido bajo",
                            Name = "Low Hold"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Sin carga",
                            Name = "No Load"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Orden",
                            Name = "Order"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Otro",
                            Name = "Other"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Por encima de la cabeza",
                            Name = "Overhead"
                        },
                        new
                        {
                            Id = 13,
                            Description = "En el hombro",
                            Name = "Shoulder"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Como maletín",
                            Name = "Suitcase"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Zercher",
                            Name = "Zercher"
                        });
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Mechanic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Mechanics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Compuesto",
                            Name = "Compound"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Aislamiento",
                            Name = "Isolation"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Tirar",
                            Name = "Pull"
                        });
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Muscle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Muscles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Adductor Magnus",
                            Name = "Adductor Magnus"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Anterior Deltoids",
                            Name = "Anterior Deltoids"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Biceps Brachii",
                            Name = "Biceps Brachii"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Biceps Femoris",
                            Name = "Biceps Femoris"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Brachialis",
                            Name = "Brachialis"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Brachioradialis",
                            Name = "Brachioradialis"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Erector Spinae",
                            Name = "Erector Spinae"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Extensor Hallucis Longus",
                            Name = "Extensor Hallucis Longus"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Flexor Carpi Radialis",
                            Name = "Flexor Carpi Radialis"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Gastrocnemius",
                            Name = "Gastrocnemius"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Gluteus Maximus",
                            Name = "Gluteus Maximus"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Gluteus Medius",
                            Name = "Gluteus Medius"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Gluteus Minimus",
                            Name = "Gluteus Minimus"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Iliopsoas",
                            Name = "Iliopsoas"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Latissimus Dorsi",
                            Name = "Latissimus Dorsi"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Obliques",
                            Name = "Obliques"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Pectoralis Major",
                            Name = "Pectoralis Major"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Posterior Deltoids",
                            Name = "Posterior Deltoids"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Quadriceps Femoris",
                            Name = "Quadriceps Femoris"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Rectus Abdominis",
                            Name = "Rectus Abdominis"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Rectus Femoris",
                            Name = "Rectus Femoris"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Rhomboids",
                            Name = "Rhomboids"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Serratus Anterior",
                            Name = "Serratus Anterior"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Soleus",
                            Name = "Soleus"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Tensor Fasciae Latae",
                            Name = "Tensor Fasciae Latae"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Teres Major",
                            Name = "Teres Major"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Teres Minor",
                            Name = "Teres Minor"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Tibialis Anterior",
                            Name = "Tibialis Anterior"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Tibialis Posterior",
                            Name = "Tibialis Posterior"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Transverse Abdominis",
                            Name = "Transverse Abdominis"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Trapezius",
                            Name = "Trapezius"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Triceps Brachii",
                            Name = "Triceps Brachii"
                        },
                        new
                        {
                            Id = 33,
                            Description = "Upper Trapezius",
                            Name = "Upper Trapezius"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Lateral Deltoids",
                            Name = "Lateral Deltoids"
                        },
                        new
                        {
                            Id = 35,
                            Description = "Anconeus",
                            Name = "Anconeus"
                        },
                        new
                        {
                            Id = 36,
                            Description = "Infraspinatus",
                            Name = "Infraspinatus"
                        },
                        new
                        {
                            Id = 37,
                            Description = "Levator Scapulae",
                            Name = "Levator Scapulae"
                        },
                        new
                        {
                            Id = 38,
                            Description = "Extensor Digitorum Longus",
                            Name = "Extensor Digitorum Longus"
                        },
                        new
                        {
                            Id = 39,
                            Description = "Supraspinatus",
                            Name = "Supraspinatus"
                        },
                        new
                        {
                            Id = 40,
                            Description = "Medial Deltoids",
                            Name = "Medial Deltoids"
                        },
                        new
                        {
                            Id = 41,
                            Description = "Subscapularis",
                            Name = "Subscapularis"
                        },
                        new
                        {
                            Id = 42,
                            Description = "Vastus Mediais",
                            Name = "Vastus Mediais"
                        });
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.MuscleGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MuscleGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Abdominales",
                            Name = "Abdominals"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Aductores",
                            Name = "Adductors"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Espalda",
                            Name = "Back"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Biceps",
                            Name = "Biceps"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Gemelos",
                            Name = "Calves"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Pecho",
                            Name = "Chest"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Antebrazos",
                            Name = "Forearms"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Gluteos",
                            Name = "Glutes"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Isquiotibiales",
                            Name = "Hamstrings"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Flexores de cadera",
                            Name = "Hip Flexors"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Quadriceps",
                            Name = "Quadriceps"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Espinillas",
                            Name = "Shins"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Hombros",
                            Name = "Shoulders"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Trapecios",
                            Name = "Trapezius"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Triceps",
                            Name = "Triceps"
                        });
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Pattern", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Patterns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Dorsiflexión de tobillo",
                            Name = "Ankle Dorsiflexion"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Flexión plantar de tobillo",
                            Name = "Ankle Plantar Flexion"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Anti-extensión",
                            Name = "Anti-Extension"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Anti-flexión",
                            Name = "Anti-Flexion"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Anti-flexión lateral",
                            Name = "Anti-Lateral Flexion"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Anti-rotación",
                            Name = "Anti-Rotational"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Extensión de codo",
                            Name = "Elbow Extension"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Flexión de codo",
                            Name = "Elbow Flexion"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Abducción de cadera",
                            Name = "Hip Abduction"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Aducción de cadera",
                            Name = "Hip Adduction"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Dominante de cadera",
                            Name = "Hip Dominant"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Extensión de cadera",
                            Name = "Hip Extension"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Rotación externa de cadera",
                            Name = "Hip External Rotation"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Flexión de cadera",
                            Name = "Hip Flexion"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Bisagra de cadera",
                            Name = "Hip Hinge"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Aducción horizontal",
                            Name = "Horizontal Adduction"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Tracción horizontal",
                            Name = "Horizontal Pull"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Empuje horizontal",
                            Name = "Horizontal Push"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Sostén isométrico",
                            Name = "Isometric Hold"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Dominante de rodilla",
                            Name = "Knee Dominant"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Flexión lateral",
                            Name = "Lateral Flexion"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Desplazamiento lateral",
                            Name = "Lateral Locomotion"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Carga en desplazamiento",
                            Name = "Loaded Carry"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Desplazamiento",
                            Name = "Locomotion"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Otro",
                            Name = "Other"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Rotacional",
                            Name = "Rotational"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Elevación escapular",
                            Name = "Scapular Elevation"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Abducción de hombro",
                            Name = "Shoulder Abduction"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Rotación externa de hombro",
                            Name = "Shoulder External Rotation"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Flexión de hombro",
                            Name = "Shoulder Flexion"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Rotación interna de hombro",
                            Name = "Shoulder Internal Rotation"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Elevación en el plano escapular del hombro",
                            Name = "Shoulder Scapular Plane Elevation"
                        },
                        new
                        {
                            Id = 33,
                            Description = "Extensión espinal",
                            Name = "Spinal Extension"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Flexión espinal",
                            Name = "Spinal Flexion"
                        },
                        new
                        {
                            Id = 35,
                            Description = "Rotación espinal",
                            Name = "Spinal Rotational"
                        },
                        new
                        {
                            Id = 36,
                            Description = "Sin clasificar*",
                            Name = "Unsorted*"
                        },
                        new
                        {
                            Id = 37,
                            Description = "Tracción vertical",
                            Name = "Vertical Pull"
                        },
                        new
                        {
                            Id = 38,
                            Description = "Empuje vertical",
                            Name = "Vertical Push"
                        },
                        new
                        {
                            Id = 39,
                            Description = "Extensión de muñeca",
                            Name = "Wrist Extension"
                        },
                        new
                        {
                            Id = 40,
                            Description = "Flexión de muñeca",
                            Name = "Wrist Flexion"
                        },
                        new
                        {
                            Id = 41,
                            Description = "Rotación interna de cadera",
                            Name = "Hip Internal Rotation"
                        });
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.PlaneOfMotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PlaneOfMotions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Plano Frontal",
                            Name = "Frontal Plane"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Plano Sagital",
                            Name = "Sagittal Plane"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Plano Transversal",
                            Name = "Transverse Plane"
                        });
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Posture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Postures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "90/90 Sentado",
                            Name = "90/90 Seated"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Puente",
                            Name = "Bridge"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Media rodilla",
                            Name = "Half Kneeling"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Colgado",
                            Name = "Hanging"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Postura del jinete",
                            Name = "Horse Stance"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Invertida",
                            Name = "Inverted"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Estocada isométrica",
                            Name = "Isometric Split Squat"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Plancha a cuatro patas con rodilla elevada",
                            Name = "Knee Hover Quadruped"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Estocada con rodilla sobre el pie",
                            Name = "Knee Over Toe Split Squat"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Apoyado de rodillas",
                            Name = "Knee Supported"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Arrodillado",
                            Name = "Kneeling"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Posición L sentado",
                            Name = "L Sit"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Marcha",
                            Name = "March"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Otra",
                            Name = "Other"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Prono (boca abajo)",
                            Name = "Prone"
                        },
                        new
                        {
                            Id = 16,
                            Description = "A cuatro patas",
                            Name = "Quadruped"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Carrera",
                            Name = "Running"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Sentado",
                            Name = "Seated"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Sentado en el suelo",
                            Name = "Seated Floor"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Sentado en caja de espinillas",
                            Name = "Shin Box Seated"
                        },
                        new
                        {
                            Id = 21,
                            Description = "De lado",
                            Name = "Side Lying"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Plancha lateral",
                            Name = "Side Plank"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Puente a una pierna",
                            Name = "Single Leg Bridge"
                        },
                        new
                        {
                            Id = 24,
                            Description = "De pie a una pierna",
                            Name = "Single Leg Standing"
                        },
                        new
                        {
                            Id = 25,
                            Description = "De pie a una pierna con rodilla flexionada",
                            Name = "Single Leg Standing Bent Knee"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Apoyado a una pierna",
                            Name = "Single Leg Supported"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Estocada",
                            Name = "Split Squat"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Postura escalonada",
                            Name = "Staggered Stance"
                        },
                        new
                        {
                            Id = 29,
                            Description = "De pie",
                            Name = "Standing"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Supino (boca arriba)",
                            Name = "Supine"
                        },
                        new
                        {
                            Id = 31,
                            Description = "De rodillas alto",
                            Name = "Tall Kneeling"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Equilibrio en la punta del pie",
                            Name = "Toe Balance"
                        },
                        new
                        {
                            Id = 33,
                            Description = "Posición L sentado agrupado",
                            Name = "Tuck L Sit"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Posición V sentado",
                            Name = "V Sit Seated"
                        },
                        new
                        {
                            Id = 35,
                            Description = "Caminando",
                            Name = "Walking"
                        },
                        new
                        {
                            Id = 36,
                            Description = "Sentado en la pared",
                            Name = "Wall Sit"
                        });
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "maximiliano_hermosilla@hotmail.com",
                            Enabled = true,
                            LastName = "Sistemas",
                            Name = "Administrador",
                            Password = "U+QpQHyCKuYC78AAH05KwA==",
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "isaias.luque@mayidev.com",
                            Enabled = true,
                            LastName = "Luque",
                            Name = "Isaias",
                            Password = "U+QpQHyCKuYC78AAH05KwA==",
                            UserName = "isaiasLuque"
                        });
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("UserId");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.WorkoutActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutActivities");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.WorkoutActivityExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("Repetitions")
                        .HasColumnType("int");

                    b.Property<int?>("RestMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("Series")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutActivityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutActivityId");

                    b.ToTable("WorkoutActivityExercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Exercise", b =>
                {
                    b.HasOne("sistemapersonaltrainer.Server.Models.BodyRegion", "BodyRegion")
                        .WithMany("Exercises")
                        .HasForeignKey("BodyRegionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.CombinationExercise", "CombinationExercise")
                        .WithMany("Exercises")
                        .HasForeignKey("CombinationExerciseId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.DifficultyLevel", "DifficultyLevel")
                        .WithMany("Exercises")
                        .HasForeignKey("DifficultyLevelId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.ExerciseMode", "ExerciseArmMode")
                        .WithMany("ArmExercises")
                        .HasForeignKey("ExerciseArmModeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.ExerciseArmType", "ExerciseArmType")
                        .WithMany("Exercises")
                        .HasForeignKey("ExerciseArmTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.ExerciseClassification", "ExerciseClassification")
                        .WithMany("Exercises")
                        .HasForeignKey("ExerciseClassificationId");

                    b.HasOne("sistemapersonaltrainer.Server.Models.ExerciseMode", "ExerciseLegMode")
                        .WithMany("LegExercises")
                        .HasForeignKey("ExerciseLegModeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.FootElevation", "FootElevation")
                        .WithMany("Exercises")
                        .HasForeignKey("FootElevationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.ForceType", "ForceType")
                        .WithMany("Exercises")
                        .HasForeignKey("ForceTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.Grip", "Grip")
                        .WithMany("Exercises")
                        .HasForeignKey("GripId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.Laterality", "Laterality")
                        .WithMany("Exercises")
                        .HasForeignKey("LateralityId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.LoadPositionEnd", "LoadPositionEnd")
                        .WithMany("Exercises")
                        .HasForeignKey("LoadPositionEndId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.Mechanic", "Mechanic")
                        .WithMany("Exercises")
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.MuscleGroup", "MuscleGroup")
                        .WithMany("Exercises")
                        .HasForeignKey("MuscleGroupId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.Posture", "Posture")
                        .WithMany("Exercises")
                        .HasForeignKey("PostureId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.Equipment", "PrimaryEquipment")
                        .WithMany("PrimaryExercises")
                        .HasForeignKey("PrimaryEquipmentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.Pattern", "PrimaryPattern")
                        .WithMany("PrimaryExercises")
                        .HasForeignKey("PrimaryPatternId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.PlaneOfMotion", "PrimaryPlaneOfMotion")
                        .WithMany("PrimaryExercises")
                        .HasForeignKey("PrimaryPlaneOfMotionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.Muscle", "PrimeMoverMuscle")
                        .WithMany("PrimeMoverExercises")
                        .HasForeignKey("PrimeMoverMuscleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.Equipment", "SecondaryEquipment")
                        .WithMany("SecondaryExercises")
                        .HasForeignKey("SecondaryEquipmentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.Muscle", "SecondaryMoverMuscle")
                        .WithMany("SecondaryMoverExercises")
                        .HasForeignKey("SecondaryMoverMuscleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.Pattern", "SecondaryPattern")
                        .WithMany("SecondaryExercises")
                        .HasForeignKey("SecondaryPatternId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.PlaneOfMotion", "SecondaryPlaneOfMotion")
                        .WithMany("SecondaryExercises")
                        .HasForeignKey("SecondaryPlaneOfMotionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.Muscle", "TertiaryMoverMuscle")
                        .WithMany("TertiaryMoverExercises")
                        .HasForeignKey("TertiaryMoverMuscleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.Pattern", "TertiaryPattern")
                        .WithMany("TertiaryExercises")
                        .HasForeignKey("TertiaryPatternId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("sistemapersonaltrainer.Server.Models.PlaneOfMotion", "TertiaryPlaneOfMotion")
                        .WithMany("TertiaryExercises")
                        .HasForeignKey("TertiaryPlaneOfMotionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("BodyRegion");

                    b.Navigation("CombinationExercise");

                    b.Navigation("DifficultyLevel");

                    b.Navigation("ExerciseArmMode");

                    b.Navigation("ExerciseArmType");

                    b.Navigation("ExerciseClassification");

                    b.Navigation("ExerciseLegMode");

                    b.Navigation("FootElevation");

                    b.Navigation("ForceType");

                    b.Navigation("Grip");

                    b.Navigation("Laterality");

                    b.Navigation("LoadPositionEnd");

                    b.Navigation("Mechanic");

                    b.Navigation("MuscleGroup");

                    b.Navigation("Posture");

                    b.Navigation("PrimaryEquipment");

                    b.Navigation("PrimaryPattern");

                    b.Navigation("PrimaryPlaneOfMotion");

                    b.Navigation("PrimeMoverMuscle");

                    b.Navigation("SecondaryEquipment");

                    b.Navigation("SecondaryMoverMuscle");

                    b.Navigation("SecondaryPattern");

                    b.Navigation("SecondaryPlaneOfMotion");

                    b.Navigation("TertiaryMoverMuscle");

                    b.Navigation("TertiaryPattern");

                    b.Navigation("TertiaryPlaneOfMotion");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Workout", b =>
                {
                    b.HasOne("sistemapersonaltrainer.Server.Models.Customer", "Customer")
                        .WithMany("Workouts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("sistemapersonaltrainer.Server.Models.User", "User")
                        .WithMany("Workouts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.WorkoutActivity", b =>
                {
                    b.HasOne("sistemapersonaltrainer.Server.Models.Workout", "Workout")
                        .WithMany("WorkoutActivities")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.WorkoutActivityExercise", b =>
                {
                    b.HasOne("sistemapersonaltrainer.Server.Models.Exercise", "Exercise")
                        .WithMany("WorkoutActivityExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("sistemapersonaltrainer.Server.Models.WorkoutActivity", "WorkoutActivity")
                        .WithMany("WorkoutActivityExercises")
                        .HasForeignKey("WorkoutActivityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutActivity");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.BodyRegion", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.CombinationExercise", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Customer", b =>
                {
                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.DifficultyLevel", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Equipment", b =>
                {
                    b.Navigation("PrimaryExercises");

                    b.Navigation("SecondaryExercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Exercise", b =>
                {
                    b.Navigation("WorkoutActivityExercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.ExerciseArmType", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.ExerciseClassification", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.ExerciseMode", b =>
                {
                    b.Navigation("ArmExercises");

                    b.Navigation("LegExercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.FootElevation", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.ForceType", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Grip", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Laterality", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.LoadPositionEnd", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Mechanic", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Muscle", b =>
                {
                    b.Navigation("PrimeMoverExercises");

                    b.Navigation("SecondaryMoverExercises");

                    b.Navigation("TertiaryMoverExercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.MuscleGroup", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Pattern", b =>
                {
                    b.Navigation("PrimaryExercises");

                    b.Navigation("SecondaryExercises");

                    b.Navigation("TertiaryExercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.PlaneOfMotion", b =>
                {
                    b.Navigation("PrimaryExercises");

                    b.Navigation("SecondaryExercises");

                    b.Navigation("TertiaryExercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Posture", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.User", b =>
                {
                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.Workout", b =>
                {
                    b.Navigation("WorkoutActivities");
                });

            modelBuilder.Entity("sistemapersonaltrainer.Server.Models.WorkoutActivity", b =>
                {
                    b.Navigation("WorkoutActivityExercises");
                });
#pragma warning restore 612, 618
        }
    }
}
